package app.pagedrop.transfer.server

import android.util.Log
import app.pagedrop.data.local.database.Book
import fi.iki.elonen.NanoHTTPD
import java.io.File
import java.io.FileInputStream
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Embedded HTTP server that serves book files to the Kindle browser.
 *
 * Routes:
 * - GET / → HTML page listing all queued books (generated by [KindlePageGenerator])
 * - GET /download/{uid} → serves the book file with Content-Disposition: attachment
 */
@Singleton
class BookServer @Inject constructor() : NanoHTTPD(PORT) {

    companion object {
        const val PORT = 8080
        private const val TAG = "BookServer"
    }

    private val lock = Any()
    private var queuedBooks: List<Book> = emptyList()

    /**
     * Set the list of books available for download.
     * Thread-safe — can be called from the UI thread.
     */
    fun setQueuedBooks(books: List<Book>) {
        synchronized(lock) {
            queuedBooks = books.toList()
        }
        Log.d(TAG, "Queued ${books.size} book(s) for transfer")
    }

    /**
     * Clear all queued books.
     */
    fun clearQueue() {
        synchronized(lock) {
            queuedBooks = emptyList()
        }
        Log.d(TAG, "Queue cleared")
    }

    override fun serve(session: IHTTPSession): Response {
        val uri = session.uri ?: "/"
        Log.d(TAG, "Request: ${session.method} $uri")

        return when {
            uri == "/" || uri.isEmpty() -> serveBookListPage()
            uri.startsWith("/download/") -> serveBookDownload(uri)
            else -> newFixedLengthResponse(
                Response.Status.NOT_FOUND,
                MIME_HTML,
                "<html><body><h1>404 - Not Found</h1></body></html>"
            )
        }
    }

    private fun serveBookListPage(): Response {
        val books = synchronized(lock) { queuedBooks.toList() }
        val html = KindlePageGenerator.generatePage(books)
        return newFixedLengthResponse(Response.Status.OK, MIME_HTML, html)
    }

    private fun serveBookDownload(uri: String): Response {
        val uidStr = uri.removePrefix("/download/")
        val uid = uidStr.toIntOrNull()
            ?: return newFixedLengthResponse(
                Response.Status.BAD_REQUEST,
                MIME_HTML,
                "<html><body><h1>400 - Invalid book ID</h1></body></html>"
            )

        val book = synchronized(lock) { queuedBooks.find { it.uid == uid } }
            ?: return newFixedLengthResponse(
                Response.Status.NOT_FOUND,
                MIME_HTML,
                "<html><body><h1>404 - Book not found</h1></body></html>"
            )

        val file = File(book.filePath)
        if (!file.exists()) {
            Log.e(TAG, "Book file not found on disk: ${book.filePath}")
            return newFixedLengthResponse(
                Response.Status.INTERNAL_ERROR,
                MIME_HTML,
                "<html><body><h1>500 - File missing</h1></body></html>"
            )
        }

        Log.i(TAG, "Serving download: ${book.fileName} (${book.fileSize} bytes) to Kindle")

        val mimeType = getMimeTypeForFormat(book.format)
        val fis = FileInputStream(file)

        return newFixedLengthResponse(Response.Status.OK, mimeType, fis, file.length()).apply {
            addHeader("Content-Disposition", "attachment; filename=\"${book.fileName}\"")
            addHeader("Content-Length", file.length().toString())
        }
    }

    private fun getMimeTypeForFormat(format: String): String {
        return when (format.uppercase()) {
            "AZW3" -> "application/x-mobi8-ebook"
            "MOBI" -> "application/x-mobipocket-ebook"
            "PDF" -> "application/pdf"
            "EPUB" -> "application/epub+zip"
            "TXT" -> "text/plain"
            else -> "application/octet-stream"
        }
    }
}
